### ISSUE TITLE
NoClassDefFoundError  with ebean 12.12.1

### ISSUE THREAD

**Issue by cleidiano** [ebean-orm/ebean-k8scache#1]
Hi I'm try to configure the ebean-k8scahce with ebean 12.12.1 but the aplication crash by NoClassDefFoundError with the stacktrace bellow:
```
Caused by: java.lang.NoClassDefFoundError: io/ebeaninternal/server/lib/DaemonThreadFactory
at io.ebeaninternal.server.cluster.socket.SocketClusterListener.<init>(SocketClusterListener.java:65)
at io.ebeaninternal.server.cluster.socket.K8sClusterBroadcast.<init>(K8sClusterBroadcast.java:74)
at io.ebeaninternal.server.cluster.K8sBroadcastFactory.create(K8sBroadcastFactory.java:43)
at io.ebeaninternal.server.cluster.ClusterManager.<init>(ClusterManager.java:36)
at io.ebeaninternal.server.core.DefaultContainer.<init>(DefaultContainer.java:43)
at io.ebeaninternal.server.DContainerFactory.create(DContainerFactory.java:15)
at io.ebean.DatabaseFactory.createContainer(DatabaseFactory.java:166)
at io.ebean.DatabaseFactory.container(DatabaseFactory.java:156)
at io.ebean.DatabaseFactory.createInternal(DatabaseFactory.java:136)
at io.ebean.DatabaseFactory.create(DatabaseFactory.java:85)
at com.picpay.atlas.persistence.PersistenceContext.database(PersistenceContext.kt:36)
at com.picpay.atlas.persistence.PersistenceContext$$EnhancerBySpringCGLIB$$d92b83f7.CGLIB$database$0(<generated>)
at com.picpay.atlas.persistence.PersistenceContext$$EnhancerBySpringCGLIB$$d92b83f7$$FastClassBySpringCGLIB$$fb8138e5.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
at com.picpay.atlas.persistence.PersistenceContext$$EnhancerBySpringCGLIB$$d92b83f7.database(<generated>)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
... 30 more
```
The issue is caused by this commit refactory https://github.com/ebean-orm/ebean/commit/ed2455f460128ec785ff38b17f380472f2502236#diff-95dd330c99dcd2c252e4845352b09a20f586247f90d2daf4649d46434b505093R1. Could this library be upgraded to the latest version of ebean-orm? If so, I could trying to submit a pull request.

**Comment by rbygrave** [comment]
> Could this library be upgraded to the latest version of ebean-orm? 

Yes, it needs to be updated.

> If so, I could trying to submit a pull request.

Great, go ahead and let me know how that goes.

Thanks, Rob.
